SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = ?
  AND DATA_TYPE IN ('char', 'nchar', 'varchar', 'nvarchar')
  AND CHARACTER_MAXIMUM_LENGTH IS NOT NULL
  AND CHARACTER_MAXIMUM_LENGTH > 0
ORDER BY ORDINAL_POSITION
